using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Spends360.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email character varying(255) NOT NULL,
                    password character varying(255) NOT NULL,
                    is_verified boolean NOT NULL DEFAULT false,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    updated_at timestamp with time zone NOT NULL DEFAULT now(),
                    created_by bigint,
                    updated_by bigint,
                    otp character varying(6),
                    otp_expires_at timestamp with time zone,
                    last_login_at timestamp with time zone,
                    last_login_ip character varying(45)
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_email" ON users (email);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "users");
        }
    }
}
